### ISSUE TITLE
How to get objects?

### ISSUE THREAD

**Issue by uzman** [ishunyu/DrawingApp#2]
hi, i m trying to implement your drawing to my project.
im wrting a small searchword app.
is it possible to get which object tapped first and last?

i have a UIView in my view controller. i tiled letters in it (10x10). i created uilabels for each letters.
all labels have tag. 
i must get which label tapped first, and last UILabel when the user touch up.

is it possible?

**Comment by ishunyu** [comment]
Hello! What you are saying doesn't sound too bad.
Is this kind of like a scrabble game?
What do you mean which label tapped first and which lable user touch up (inside?).
Are you talking about kind of a swipey like thing?
I think this is what you are trying to do?
http://www.androidtapp.com/scramble-with-friends/

**Comment by uzman** [comment]
its just simple search word game. i just want to draw straight line, (horizontal, vertical and diagonal).
i put the uilabels in the uiview. each uilabel has one letter.
when the user tap first, i must get the point and which uilabel.
while user moves it must draw line, when finger is touched up i must get last point and uilabel.

then it must draw the line. (just horizontal, vertical and diagonal-45).

**Comment by uzman** [comment]
here is the sample app:
https://itunes.apple.com/en/app/wordsearch-unlimited-free/id306245714?mt=8

**Comment by ishunyu** [comment]
You can definitely do that.
In fact, that's exactly how I draw a straight line.
If you check the code for that then you should be able to see how I did it.
