### ISSUE TITLE
selection

### ISSUE THREAD

**Issue by misbell** [ishunyu/DrawingApp#3]
Hey man, great code.

I noticed there's code to select objects in the source but doesn't seem to be implemented, unless I'm missing something. You ever do an update to this?

I learned a LOT from reading this code and felt so dumb when I realized how you draw a straight line :-) very nice.

**Comment by ishunyu** [comment]
Hi!
Thank you so much for looking at this.
The selection mechanism should work, though it might be a little un-intuitive.
When you have drawn a shape, go ahead try to click it.
A box with dashed line should outline the shape, and you can drag it around or change its properties.
Try it!
